### ISSUE TITLE
Bootloader usage

### ISSUE THREAD

**Issue by TinManAkshay** [khoih-prog/ESP_AT_Lib#1]
Hi,

I looked at your library and its pretty to understand. I'd like to test the examples on my custom board having SAMD51 MCU and Ublox NINA W152 chip (has an ESP32 core integrated).

I've been meaning to inquire regarding a bootloader being used in your examples. I've a custom board around Adafruit feather M4 express. What bootloader (.bin file) do I have to flash from the folder "AT firmware" into the wifi chip before I use one of you examples? 

NOTE: - I have an UART interface capability on the wifi chip including TX, RX, CTS, RTS, DTS and DTR pins.

Thanks,
Akshay

**Comment by khoih-prog** [comment]
Hi @tcpipchip,

As you're an expert in Ublox chip, could you please help here.

Thanks and Best Regards,

**Comment by khoih-prog** [comment]
Just a suggestion, why don't you use much better WiFiNINA, instead of te worse AT-command Firmware?

Check this [**u-blox nina** b #1](https://github.com/khoih-prog/WiFiNINA_Generic/issues/1)

**Comment by TinManAkshay** [comment]
Hi @khoih-prog ,

Thank you so much for the quick response. Appreciate it.

I believe WiFiNINA uses SPI interface to talk to the Ublox WiFi chip, correct? However, in our custom board, we only have UART interface to communicate with Ublox W152 chip.

So far, according to the datasheet, I am able to send AT commands to the chip and receive the responses back accordingly, using Arduino IDE. For an instance, I can connect to the Wifi network and set-up an UDP address and port number. However, I could not figure out how to send/receive the udp packets using UART interface. 

On top of that, I am having an issue like as follows:

1. I am using "Espressif esptool.py" tool and "s-center" (which is an Ublox software) to establish a contact with a device. But I cannot able to do that. Eventually, I couldn't flash a bootloader (.bin files) so that I could use existing Arduino libraries made for UART interface with AT commands like your library.

I really need a right direction to move to. I'd appreciate any sort of advice and suggestion here.

Thanks,
Akshay

**Comment by khoih-prog** [comment]
1. For UDP/WebServer, you can use my other [**ESP8266_AT_WebServer** library](https://github.com/khoih-prog/ESP8266_AT_WebServer). Have a look at [**UdpSendReceive** example](https://github.com/khoih-prog/ESP8266_AT_WebServer/tree/master/examples/UdpSendReceive)
2. 

> I believe WiFiNINA uses SPI interface

Correct. Too bad you have to use Serial and AT-command. It's much better to change the HW/SW design in order to use better SPI / WiFiNINA, if possible.

3. Sorry, you have to do more research yourself, or post on the Arduino / Adafruit for help. There is many and very easy way to load AT-command FW onto ESP32-based boards.

The working FW for ESP32 is here

[**AT_version_2.1.0.0_dev**.zip](https://github.com/khoih-prog/ESP8266_AT_WebServer/blob/master/AT_Firmwares/AT_version_2.1.0.0_dev.zip)

or 

[**AT_version_2.1.0.0_dev**](https://github.com/khoih-prog/ESP_AT_Lib/blob/master/AT_Firmwares/AT_version_2.1.0.0_dev.zip)

and [**Instructions to load FW**](https://github.com/khoih-prog/ESP8266_AT_WebServer#2-tested-ok-with-esp32-at-shields)

---

I don't have time now to help you further as this is not a bug or have nothing to do with this library

Good Luck,

**Comment by khoih-prog** [comment]
Have a look at [SAMD51 Itsy-Bitsy M4](https://github.com/khoih-prog/ESP8266_AT_WebServer#1-samd51-itsy-bitsy-m4) using ESP8266 AT-command shield. Working OK, only worse performance than ESP32 alone.

![image](https://user-images.githubusercontent.com/57012152/127942071-e9042032-a3e1-4933-9165-01ca76311bb0.png)

**Comment by tcpipchip** [comment]
Hi
 Ublox W152 chip has protect code, if you erase it, you cant more recover, i guess!
It can be used with SPI too, but now enough info about

**Comment by tcpipchip** [comment]
But, i dont know if this compatible with WIFININA software

**Comment by TinManAkshay** [comment]
Hi @tcpipchip ,

What do you recommend whether I should make changes to the current design and introduce SPI interface to the Ublox wifi chip? Then, use WifiNINA?

Can't I use this library with UART interface? To use this library, I've got to erase the current bootloader in the chip and flash the new one which this library requires, correct? I'm having issues to establish contact with a device while flashing the AT firmware which this library requires.

Could you please help me with more information here. I'd highly appreciate that.

Thanks,
Akshay

**Comment by TinManAkshay** [comment]
Hi @khoih-prog ,

As per your last comments, could you please share what dev board or wifi chip you used to get your examples up and running?

You must have first flashed AT firmware onto the wifi chip using Espressif esptool.py before you uploaded the example.ino sketch, correct?

**Comment by tcpipchip** [comment]
@TinManAkshay 
You will find here
https://learn.adafruit.com/adding-a-wifi-co-processor-to-circuitpython-esp8266-esp32/firmware-files

**Comment by TinManAkshay** [comment]
Hi @khoih-prog ,

Wanted to follow-up since my last comment. Please let me know what ESP32 dev board you used for your libraries?

**Comment by khoih-prog** [comment]
Just a dirt-cheap ESP8266-01 AT-command
![ESP8266-01](https://user-images.githubusercontent.com/57012152/128432926-6481a9c0-af69-4834-bcc3-1f1a23e5dc8f.png)
